const ApolloServer = require('apollo-server-express').ApolloServer;
const express = require('express');
const neo4j = require('neo4j-driver').v1;
const {makeAugmentedSchema} = require('neo4j-graphql-js');
const dotenv = require('dotenv');

// set environment variables from ../.env
dotenv.config();

const app = express();

/*
 * Create an executable GraphQL schema object from GraphQL type definitions
 * including autogenerated queries and mutations.
 * Optionally a config object can be included to specify which types to include
 * in generated queries and/or mutations. Read more in the docs:
 * https://grandstack.io/docs/neo4j-graphql-js-api.html#makeaugmentedschemaoptions-graphqlschema
 */

const {fieldsMapping} =  require("./consts");

let resolvers = {
  Query: {
    async Edge(obj, params, ctx, resolveInfo) {
      let db = ctx.db;
      return await db.getAllEdges();
    },
    async Node(obj, params, ctx, resolveInfo) {
      let db = ctx.db;
      return await db.getAllNodes();
    }
  },
  Mutation: {
    async CreateNode(obj, params, ctx, resolveInfo) {
      let db = ctx.db;
      return await db.insertNode(params);
    },
    async UpdateNode(obj, params, ctx, resolveInfo) {
      let db = ctx.db;
      return await db.updateNodeByID(params.id, params);
    },
    async DeleteNode(obj, params, ctx, resolveInfo) {
      let db = ctx.db;
      let result = await db.deleteNodeByID(params.id);
      return result;
    },

    async CreateEdge(obj, params, ctx, resolveInfo) {
      let db = ctx.db;
      let startNode = params.startNode;
      let stopNode = params.stopNode;
      delete params.startNode;
      delete params.stopNode;

      // everything else is edgeInfo
      let edgeInfo = params;

      let result = {
        start: {
          properties: await db.insertNode(startNode)
        },
        end: {
          properties: await db.insertNode(stopNode)
        },
        relationship: {
          properties: await db.insertEdge(startNode, stopNode, edgeInfo)
        },
      };

      return result;
    },
    async DeleteEdge(obj, params, ctx, resolveInfo) {
      let db = ctx.db;
      let startNode = params.startNode;
      let stopNode = params.stopNode;
      delete params.startNode;
      delete params.stopNode;

      // everything else is edgeInfo
      let edgeInfo = params;

      let result = {
        start: {
          properties: await db.insertNode(startNode)
        },
        end: {
          properties: await db.insertNode(stopNode)
        },
        relationship: {
          properties: await db.insertEdge(startNode, stopNode, edgeInfo)
        },
      };

      return result;
    },

  }
};

resolvers.Node = {};
for (const nodeProperty of fieldsMapping.startNode) {
  resolvers.Node[nodeProperty.name] = (obj, params, ctx, resolveInfo) => {
    if (!obj[nodeProperty.name]) {
      return null;
    }
    return obj[nodeProperty.name];
  };
}

resolvers.Edge = {
  startNode(obj, params, ctx, resolveInfo) {
    return obj.start.properties;
  },
  stopNode(obj, params, ctx, resolveInfo) {
    return obj.end.properties;
  }
};
for (const edgeProperty of fieldsMapping.edgeInfo) {
  resolvers.Edge[edgeProperty.name] = (obj, params, ctx, resolveInfo) => {
    return obj.relationship.properties[edgeProperty.name]
  };
}

const typeDefs = require('./graphql-schema').typeDefs;
const schema = makeAugmentedSchema({
  typeDefs,
  resolvers,
});


const db = require("./neo4j.js"); // for the Edge's manual generated Query fields
db.init();

const server = new ApolloServer({
  context: { db },
  schema: schema,
  introspection: true,
  playground: true,
});

// Specify port and path for GraphQL endpoint
const port = process.env.GRAPHQL_LISTEN_PORT || 4001;
const path = '/graphql';

/*
 * Optionally, apply Express middleware for authentication, etc
 * This also also allows us to specify a path for the GraphQL endpoint
 */
server.applyMiddleware({ app, path });

app.listen({ port, path }, () => {
  // eslint-disable-next-line
  console.log(`GraphQL server ready at http://localhost:${port}${path}`);
});
